# Generated by Django 5.1.6 on 2025-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "time",
                    models.CharField(
                        blank=True, default="11 March 2025", max_length=100
                    ),
                ),
                ("post_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("subject", models.CharField(max_length=1000)),
                ("message", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("image_path", models.CharField(blank=True, max_length=500, null=True)),
                ("content", models.TextField()),
                (
                    "time",
                    models.CharField(
                        blank=True, default="11 March 2025", max_length=100
                    ),
                ),
                ("likes", models.IntegerField(blank=True, default=0, null=True)),
                ("user_id", models.IntegerField()),
            ],
        ),
    ]
