# Generated by Django 5.1.6 on 2025-03-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_path",
            field=models.ImageField(blank=True, null=True, upload_to="images/posts"),
        ),
    ]
